name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0=py_0
  - attrs=19.3.0=py_0
  - blas=1.0=mkl
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2020.1.1=0
  - cachetools=3.1.1=py_0
  - certifi=2019.11.28=py36_1
  - cffi=1.14.0=py36ha419a9e_0
  - chardet=3.0.4=py36h9f0ad1d_1006
  - click=7.0=py36_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py36_0
  - cryptography=2.8=py36hb32ad35_1
  - curl=7.65.3=h2a8f88b_0
  - django=2.2.5=py36_1
  - earthengine-api=0.1.216=pyh8c360ce_0
  - expat=2.2.5=he025d50_0
  - fiona=1.8.4=py36h22081e2_0
  - freexl=1.0.5=hfa6e2cd_0
  - future=0.18.2=py36h9f0ad1d_1
  - gdal=2.3.3=py36hdf43c64_0
  - geos=3.7.1=h33f27b4_0
  - google-api-core=1.16.0=py36h21ff451_1
  - google-api-python-client=1.8.0=pyh8c360ce_0
  - google-auth=1.11.2=py_0
  - google-auth-httplib2=0.0.3=py_3
  - google-cloud-core=1.3.0=py_0
  - google-cloud-storage=1.26.0=py_0
  - google-resumable-media=0.5.0=py_1
  - googleapis-common-protos=1.51.0=py36h21ff451_1
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.4=h7ebc959_0
  - httplib2=0.17.0=py36h9f0ad1d_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - intel-openmp=2019.4=245
  - jpeg=9b=hb83a4c4_2
  - kealib=1.4.7=h07cbb95_6
  - krb5=1.16.1=hc04afaa_7
  - libboost=1.67.0=hd9e427e_4
  - libcurl=7.65.3=h2a8f88b_0
  - libgdal=2.3.3=h10f50ba_0
  - libiconv=1.15=h1df5818_7
  - libkml=1.3.0=he5f2a48_4
  - libnetcdf=4.6.1=h411e497_2
  - libpng=1.6.37=h2a8f88b_0
  - libpq=11.2=h3235a2c_0
  - libprotobuf=3.11.4=h1a1b453_0
  - libspatialite=4.3.0a=hc36aec2_19
  - libssh2=1.8.2=h7a1dbc1_0
  - libtiff=4.0.10=hb898794_2
  - libxml2=2.9.9=h464c3ec_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py36hb782905_0
  - mkl_fft=1.0.14=py36h14836fe_0
  - mkl_random=1.1.0=py36h675688f_0
  - munch=2.5.0=py_0
  - numpy=1.16.5=py36h19fb1c0_0
  - numpy-base=1.16.5=py36hc3f5095_0
  - openssl=1.1.1e=he774522_0
  - pcre=8.43=ha925a31_0
  - pip=19.2.3=py36_0
  - postgresql=11.2=h3235a2c_0
  - proj4=5.2.0=ha925a31_1
  - protobuf=3.11.4=py36he025d50_0
  - psycopg2=2.8.3=py36h7a1dbc1_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.2=py_0
  - pysocks=1.7.1=py36h9f0ad1d_1
  - python=3.6.9=h5500b2f_0
  - python_abi=3.6=1_cp36m
  - pytz=2019.2=py_0
  - rasterio=1.0.21=py36h6bd7d87_0
  - rasterstats=0.14.0=py_0
  - rsa=4.0=py_0
  - setuptools=41.2.0=py36_0
  - shapely=1.6.4=py36h222a598_0
  - simplejson=3.17.0=py36hfa6e2cd_0
  - six=1.12.0=py36_0
  - snuggs=1.4.7=py_0
  - sqlite=3.29.0=he774522_0
  - sqlparse=0.3.0=py_0
  - tk=8.6.8=hfa6e2cd_0
  - uritemplate=3.0.1=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wheel=0.33.6=py36_0
  - win_inet_pton=1.1.0=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - xerces-c=3.2.2=ha925a31_0
  - xz=5.2.4=h2fa13f4_4
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
  - pip:
    - amqp==2.5.2
    - astroid==2.3.2
    - billiard==3.6.3.0
    - boto3==1.12.32
    - botocore==1.15.32
    - branca==0.4.0
    - celery==4.4.2
    - colorama==0.4.1
    - defusedxml==0.6.0
    - diff-match-patch==20181111
    - django-colorful==1.3
    - django-cors-headers==3.2.1
    - django-crispy-forms==1.8.0
    - django-extensions==2.2.8
    - django-geojson==3.0.0
    - django-import-export==1.2.0
    - django-jsonfield==1.4.0
    - django-leaflet==0.24.0
    - django-raster==0.8
    - djangorestframework==3.10.3
    - djangorestframework-gis==0.15
    - docutils==0.15.2
    - et-xmlfile==1.0.1
    - folium==0.10.1
    - gdal2mbtiles==2.1.2
    - gdal2tiles==0.1.6
    - geojson==2.5.0
    - idna==2.8
    - importlib-metadata==1.6.0
    - isort==4.3.21
    - jdcal==1.4.1
    - jinja2==2.11.1
    - jmespath==0.9.5
    - kombu==4.6.8
    - lazy-object-proxy==1.4.3
    - markuppy==1.14
    - markupsafe==1.1.1
    - mccabe==0.6.1
    - numexpr==2.7.1
    - oauthlib==3.1.0
    - odfpy==1.4.0
    - openpyxl==3.0.0
    - pillow==7.0.0
    - pyjwt==1.7.1
    - pylint==2.4.3
    - pyproj==2.6.0
    - python-dateutil==2.8.1
    - python3-openid==3.1.0
    - pyvips==2.1.8
    - pyyaml==5.1.2
    - requests==2.22.0
    - requests-oauthlib==1.2.0
    - s3transfer==0.3.3
    - social-auth-app-django==3.1.0
    - social-auth-core==3.2.0
    - subprocess32==3.5.4
    - tablib==0.14.0
    - typed-ast==1.4.0
    - urllib3==1.25.6
    - vine==1.3.0
    - webcolors==1.11.1
    - wrapt==1.11.2
    - xlrd==1.2.0
    - xlwt==1.3.0
    - zipp==3.1.0
prefix: D:\Programs\Anaconda\envs\myenv

